
USE companyDB;
CREATE TABLE  EMPLOYEES (
Employee_id INT PRIMARY KEY AUTO_INCREMENT,
FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL 
);
USE companydb;
ALTER TABLE EMPLOYEES
ADD  HIREDATE DATE;
ALTER TABLE EMPLOYEES 
ADD  SALARY INT;
SET SQL_SAFE_UPDATES = 0;
UPDATE EMPLOYEES
SET SALARY = 4800
WHERE employee_id = 2;
UPDATE EMPLOYEES
SET HIREDATE = '2021-08-01'
WHERE FIRSTNAME = 'DAVID';
SET SQL_SAFE_UPDATES = 0;
DELETE FROM Employees
WHERE SALARY < 5000;
DELETE FROM Employees
WHERE Employee_id = 1;
SELECT * FROM Employees
WHERE SALARY > 5000;
select * from employees
order by hiredate desc;

